export type BuildoutCategory = 'capital' | 'cooling' | 'policy';

export type BuildoutEvent = {
  id: string;
  title: string;
  entityName: string;
  entityType: string;
  category: BuildoutCategory;
  subcategory?: string;
  geography?: string;
  jurisdiction?: string;
  announcedSpend?: string;
  currency?: string;
  coolingType?: string;
  supplier?: string;
  densityIndicator?: string;
  policyType?: string;
  impactLabel?: 'High' | 'Medium' | 'Low';
  status?: string;
  publicationStatus?: 'approved' | 'draft' | 'archived';
  confidence?: 'Confirmed' | 'Guided' | 'Derived' | 'Estimated';
  eventDate: string;
  summary: string;
  sourceUrl?: string;
  sourceLabel?: string;
  createdAt: string;
  updatedAt: string;
};

export const buildoutEvents: BuildoutEvent[] = [
  {
    id: 'evt-001',
    title: 'AWS $100B+ US Data Center Investment',
    entityName: 'Amazon Web Services',
    entityType: 'Hyperscaler',
    category: 'capital',
    geography: 'United States',
    announcedSpend: '100000000000',
    currency: 'USD',
    eventDate: '2026-01-15',
    summary: 'Amazon guided to more than $100B in 2025 capex, with the vast majority for AWS AI and cloud infrastructure.',
    sourceUrl: '#',
    sourceLabel: 'Company Announcement',
    publicationStatus: 'approved',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-002',
    title: 'Microsoft 1.5GW Nuclear PPA',
    entityName: 'Microsoft',
    entityType: 'Hyperscaler',
    category: 'capital',
    geography: 'United States',
    announcedSpend: 'Undisclosed',
    eventDate: '2026-02-10',
    summary: 'Microsoft signed a major grid-scale nuclear power purchase agreement to secure firm, carbon-free baseload power for upcoming AI training clusters.',
    sourceUrl: '#',
    sourceLabel: 'Press Release',
    publicationStatus: 'approved',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-003',
    title: 'NVIDIA 1GW Liquid Cooling Reference Design',
    entityName: 'NVIDIA & Trane Technologies',
    entityType: 'Supplier Partnership',
    category: 'cooling',
    coolingType: 'Direct-to-Chip Liquid Cooling',
    supplier: 'Trane Technologies',
    densityIndicator: '120kW+ per rack',
    announcedSpend: 'Undisclosed',
    eventDate: '2026-03-05',
    summary: 'Trane Technologies optimized the NVIDIA Omniverse DSX blueprint, freeing 22MW of cooling capacity and improving thermal performance for next-generation AI clusters.',
    sourceUrl: '#',
    sourceLabel: 'Technical Brief',
    publicationStatus: 'approved',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-004',
    title: 'Virginia Data Center Tax Incentive Review',
    entityName: 'State of Virginia',
    entityType: 'Government',
    category: 'policy',
    jurisdiction: 'Virginia, USA',
    policyType: 'Tax Legislation',
    impactLabel: 'High',
    status: 'Under Review',
    announcedSpend: 'Undisclosed',
    eventDate: '2026-03-20',
    summary: 'Virginia lawmakers initiated a review of data center tax incentives, citing grid strain and land use concerns in Loudoun and Prince William counties.',
    sourceUrl: '#',
    sourceLabel: 'Legislative Tracker',
    publicationStatus: 'approved',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-005',
    title: 'Meta 1.1GW PPA with Constellation Energy',
    entityName: 'Meta',
    entityType: 'Hyperscaler',
    category: 'capital',
    geography: 'United States',
    announcedSpend: 'Undisclosed',
    eventDate: '2026-03-25',
    summary: 'Meta signed a 1.1GW power purchase agreement with Constellation Energy for the Clinton Clean Energy Center to support its $65B 2026 AI infrastructure buildout.',
    sourceUrl: '#',
    sourceLabel: 'Market Filing',
    publicationStatus: 'approved',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-006',
    title: 'Eaton & Boyd Thermal Acquisition Integration',
    entityName: 'Eaton',
    entityType: 'Supplier',
    category: 'cooling',
    coolingType: 'Hybrid Liquid/Air',
    supplier: 'Eaton',
    announcedSpend: 'Undisclosed',
    eventDate: '2026-02-28',
    summary: 'Eaton completed integration of Boyd Thermal, offering a unified "chip-to-grid" power and cooling management system for high-density AI factories.',
    sourceUrl: '#',
    sourceLabel: 'Earnings Call',
    publicationStatus: 'approved',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-007',
    title: 'Texas ERCOT Interconnection Queue Reform',
    entityName: 'ERCOT',
    entityType: 'Grid Operator',
    category: 'policy',
    jurisdiction: 'Texas, USA',
    policyType: 'Grid Regulation',
    impactLabel: 'High',
    status: 'Implemented',
    announcedSpend: 'Undisclosed',
    eventDate: '2026-01-30',
    summary: 'ERCOT implemented new interconnection queue rules prioritizing projects with secured large-load agreements, impacting merchant power data center developments.',
    sourceUrl: '#',
    sourceLabel: 'Regulatory Filing',
    publicationStatus: 'approved',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-008',
    title: 'NextEra Energy $15B Renewables Expansion',
    entityName: 'NextEra Energy',
    entityType: 'Power Generation',
    category: 'capital',
    geography: 'United States',
    announcedSpend: '15000000000',
    currency: 'USD',
    eventDate: '2026-03-12',
    summary: 'Forward renewables and clean‑energy build‑out program on the order of $15B.',
    sourceUrl: '#',
    sourceLabel: 'Investor Day',
    publicationStatus: 'approved',
    createdAt: '2026-04-08T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-009',
    title: 'Equinix $8B xScale Data Center JV',
    entityName: 'Equinix',
    entityType: 'REIT / Operator',
    category: 'capital',
    geography: 'Global',
    announcedSpend: '8000000000',
    currency: 'USD',
    eventDate: '2026-02-20',
    summary: 'xScale joint venture program for hyperscale data centers totaling about $8B.',
    sourceUrl: '#',
    sourceLabel: 'Press Release',
    publicationStatus: 'approved',
    createdAt: '2026-04-08T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-010',
    title: 'Vertiv $2.5B Manufacturing Capacity Expansion',
    entityName: 'Vertiv',
    entityType: 'Power & Cooling',
    category: 'capital',
    geography: 'North America & EMEA',
    announcedSpend: '2500000000',
    currency: 'USD',
    eventDate: '2026-01-25',
    summary: 'Vertiv completed a $2.1B bond and $2.5B revolver to refinance debt and expand manufacturing capacity; we use $2.5B as the OEM capacity proxy.',
    sourceUrl: '#',
    sourceLabel: 'Earnings Call',
    publicationStatus: 'approved',
    createdAt: '2026-04-08T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-011',
    title: 'Broadcom $4B Custom Silicon R&D Facility',
    entityName: 'Broadcom',
    entityType: 'Chips & Networking',
    category: 'capital',
    geography: 'United States',
    announcedSpend: 'Undisclosed',
    currency: 'USD',
    eventDate: '2026-03-01',
    summary: 'Broadcom announced a $4B investment in a new R&D and testing facility focused on next-generation custom silicon and high-speed optical interconnects for AI clusters.',
    sourceUrl: '#',
    sourceLabel: 'Company Announcement',
    publicationStatus: 'approved',
    createdAt: '2026-04-08T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-012',
    title: 'UAE $30B Sovereign AI Infrastructure Fund',
    entityName: 'MGX',
    entityType: 'Sovereign / Gov\'t',
    category: 'capital',
    geography: 'Middle East & Global',
    announcedSpend: '30000000000',
    currency: 'USD',
    eventDate: '2026-03-15',
    summary: 'Announced $30B UAE sovereign fund targeting AI infrastructure (data centers, chips, power).',
    sourceUrl: '#',
    sourceLabel: 'Government Press Release',
    publicationStatus: 'approved',
    createdAt: '2026-04-08T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-013',
    title: 'Digital Realty $12B Development Pipeline',
    entityName: 'Digital Realty',
    entityType: 'REIT / Operator',
    category: 'capital',
    geography: 'Global',
    announcedSpend: '12000000000',
    currency: 'USD',
    eventDate: '2026-04-05',
    summary: 'Company disclosures indicate a development pipeline of roughly $12B.',
    sourceUrl: '#',
    sourceLabel: 'Investor Presentation',
    publicationStatus: 'approved',
    createdAt: '2026-04-08T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  },
  {
    id: 'evt-014',
    title: 'Google $5B Subsea Cable & Network Expansion',
    entityName: 'Google',
    entityType: 'Hyperscaler',
    category: 'capital',
    geography: 'Global',
    announcedSpend: '5000000000',
    currency: 'USD',
    eventDate: '2026-02-15',
    summary: 'Announced subsea cable and network expansion program totaling ~$5B.',
    sourceUrl: '#',
    sourceLabel: 'Company Blog',
    publicationStatus: 'approved',
    createdAt: '2026-04-08T00:00:00Z',
    updatedAt: '2026-04-09T00:00:00Z',
  }
];

export const buildoutKPIs = {
  totalTrackedCapex: '$245B+',
  trackedProjects: 142,
  coolingDisclosures30d: 18,
  activePolicyDevelopments: 24,
  lastUpdated: '2026-04-08T17:00:00Z'
};
