export type RequiredTier = 'free' | 'essentials' | 'pro';

export const PAGE_METADATA = [
  { path: '/', name: 'Home', description: 'Landing page', isPaid: false, requiredTier: 'free' as RequiredTier },
  { path: '/about', name: 'About', description: 'About TPL', isPaid: false, requiredTier: 'free' as RequiredTier },
  { path: '/get-access', name: 'Get Access', description: 'Pricing and plans', isPaid: false, requiredTier: 'free' as RequiredTier },
  { path: '/enterprise-request', name: 'Enterprise Request', description: 'Enterprise consultation form', isPaid: false, requiredTier: 'free' as RequiredTier },
  { path: '/signup', name: 'Signup', description: 'User registration', isPaid: false, requiredTier: 'free' as RequiredTier },
  { path: '/login', name: 'Login', description: 'User login', isPaid: false, requiredTier: 'free' as RequiredTier },
  { path: '/article', name: 'Flagship Article', description: 'Main research article', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/reports', name: 'Operator Reports', description: 'List of reports', isPaid: false, requiredTier: 'free' as RequiredTier },
  { path: '/monitor', name: 'Constraint Monitor', description: 'Monitor overview', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/monitor/methodology', name: 'Monitor Methodology', description: 'Methodology details', isPaid: false, requiredTier: 'free' as RequiredTier },
  { path: '/monitor/report', name: 'Monitor Report', description: 'Full quarterly report', isPaid: true, requiredTier: 'pro' as RequiredTier },
  { path: '/buildout-tracker', name: 'Buildout Tracker', description: 'Buildout tracker hub', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/market-tracker', name: 'Market Tracker', description: 'Market tracker hub', isPaid: true, requiredTier: 'pro' as RequiredTier },
  { path: '/forecast', name: 'Forecast', description: 'Forecast index', isPaid: true, requiredTier: 'pro' as RequiredTier },
  { path: '/constraint-atlas', name: 'Constraint Atlas', description: 'Constraint atlas overview', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/constraint-atlas/interactive', name: 'Interactive Constraint Atlas', description: 'Interactive constraint simulator', isPaid: true, requiredTier: 'pro' as RequiredTier },
  { path: '/failures', name: 'Failure Case Studies', description: 'Failure case studies index', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/failures/midwest-ai-campus', name: 'Midwest AI Campuses', description: 'Midwest AI Campuses failure case study', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/intelligence', name: 'Intelligence Archive', description: 'Archive of past reports', isPaid: true, requiredTier: 'pro' as RequiredTier },
  { path: '/constraints/national/power', name: 'Power Outlook', description: 'Power constraint outlook', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/constraints/national/cooling', name: 'Cooling Outlook', description: 'Cooling constraint outlook', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/constraints/national/water', name: 'Water Outlook', description: 'Water constraint outlook', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/constraints/national/permitting', name: 'Permitting Outlook', description: 'Permitting constraint outlook', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/constraints/national/supply-chain', name: 'Supply Chain Outlook', description: 'Supply chain constraint outlook', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/constraints/national/labor', name: 'Labor Outlook', description: 'Labor constraint outlook', isPaid: true, requiredTier: 'essentials' as RequiredTier },
  { path: '/markets/northern-va', name: 'Northern Virginia Market', description: 'Northern Virginia market dossier', isPaid: true, requiredTier: 'pro' as RequiredTier },
  { path: '/markets/phoenix', name: 'Phoenix Market', description: 'Phoenix market dossier', isPaid: true, requiredTier: 'pro' as RequiredTier },
  { path: '/markets/texas', name: 'Texas Market', description: 'Texas market dossier', isPaid: true, requiredTier: 'pro' as RequiredTier },
];
