export interface GlossaryTerm {
  term: string;
  definition: string;
  category: 'Infrastructure' | 'Water' | 'Power' | 'Policy' | 'Construction';
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    term: "PUE (Power Usage Effectiveness)",
    definition: "A ratio that describes how efficiently a computer data center uses energy; specifically, how much energy is used by the computing equipment, in contrast to cooling and other overhead.",
    category: "Infrastructure"
  },
  {
    term: "WUE (Water Usage Effectiveness)",
    definition: "A metric used to measure the sustainability of data centers in terms of water usage and its relation to energy consumption.",
    category: "Water"
  },
  {
    term: "Baseload Power",
    definition: "The minimum amount of electric power delivered or required over a given period of time at a steady rate.",
    category: "Power"
  },
  {
    term: "Evaporative Cooling",
    definition: "A method of cooling that uses the evaporation of water to lower the temperature of the air, commonly used in data centers but highly water-intensive.",
    category: "Water"
  },
  {
    term: "Grid Interconnection Queue",
    definition: "The list of energy projects waiting for approval to connect to the power grid, often a major bottleneck for new data center construction.",
    category: "Power"
  },
  {
    term: "Hyperscale Data Center",
    definition: "Large-scale facilities built by companies like Amazon, Google, and Microsoft to support massive cloud and AI workloads.",
    category: "Infrastructure"
  },
  {
    term: "Zoning Variance",
    definition: "A request to deviate from current zoning requirements, often necessary for large industrial compute projects in non-industrial areas.",
    category: "Policy"
  },
  {
    term: "Behind-the-Meter (BTM)",
    definition: "Energy generated and consumed on-site without passing through a utility meter, often used to bypass grid constraints.",
    category: "Power"
  },
  {
    term: "Thermal Design Power (TDP)",
    definition: "The maximum amount of heat generated by a computer chip that the cooling system is designed to dissipate under any workload.",
    category: "Infrastructure"
  },
  {
    term: "Brownfield Site",
    definition: "A property whose expansion, redevelopment, or reuse may be complicated by the presence or potential presence of a hazardous substance, pollutant, or contaminant.",
    category: "Construction"
  }
];
